name: Build APK

on:
  push:
    branches:
      - cnfont  # sesuaikan dengan branch Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # 🔥 WAJIB DITAMBAHKAN: Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          android-sdk-file: "platforms;android-34|build-tools;34.0.0"

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      # 🔥 PERBAIKAN: Gunakan task yang benar dengan modul :app:
      - name: Build Debug APK
        run: |
          ./gradlew clean
          ./gradlew :app:assembleDebug --refresh-dependencies

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ScreenTranslator-APK
          path: app/build
